services:
  pyspark:
    build: .
    ports:
      - "8888:8888"  # Jupyter Lab
      - "4040:4040"  # Spark UI
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    environment:
      - JUPYTER_ENABLE_LAB=yes